# Generated by Django 3.0.6 on 2020-05-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='img',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
    ]
