# Generated by Django 3.0.6 on 2020-05-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esite', '0002_shoes_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField(max_length=100)),
            ],
        ),
    ]
